apiVersion: v1
kind: Pod
metadata:
  name: pod-datacenter
  labels:
    run: pod-datacenter
spec:
  containers:
  - name: container-datacenter
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pvc
    persistentVolumeClaims:
      claimName: pvc-datacenter
