apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana        # its label deployment, must match
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32000
  type: NodePort
    
