apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: print-envars-greeting
  name: print-envars-greeting
spec:
  containers:
  - image: bash
    name: print-env-container
    command:
    - /bin/sh
    - -c
    - echo "$(GREETING) $(COMPANY) $(GROUP)"
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "Nautilus"
    - name: GROUP
      value: "Datacenter"
  restartPolicy: Never
