apiVersion: v1
kind: Service
metadata:
  labels:
    app: iron-gallery-service-datacenter
  name: iron-gallery-service-datacenter
  namespace: iron-namespace-datacenter
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32678
  selector:
    run: iron-gallery
  type: NodePort
